version: 2
jobs:
  lint_js:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: npm install
      - run: npm run lint:js:ci
  lint_css:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: npm install
      - run: npm run lint:css:ci
  cypress:
    docker:
      - image: quay.io/quintype/docker-base:cypress-3.1.1
      - image: quay.io/quintype/malibu    
    steps:
      - checkout
      - run: /node_modules/.bin/cypress run    
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint_js
      - lint_css
      - cypress
