version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: npm install
      - run: npm run lint:ci
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
