asset_host: http://localhost:8080
sketches_host: http://quintype-demo.quintype.io
host_to_api_host:
  help.lvh.me: https://user-documentation.quintype.io
host_to_automatic_api_host:
  - "-web"
  - ".malibu"
